title: JIJI GEORGE
author: jiji
email: your-email@domain.com
description: > I am pleased to be able to share that the New Hyde Park – Garden City Park UFSD received permission from the State to resume offering free lunch to all enrolled students under the National School Lunch Program, similar to what we offered last year. Additionally, free breakfast will be available as well.
Since it is entirely possible that the State will run out of funding prior to the end of the school year, it is strongly recommended that those families who qualify for Free or Reduced Price Meals, fill out the forms that are on the district’s website just to be safe. In order to determine if you are eligible for this benefit please click on the following hyperlink to visit the district’s webpage for meal services and review the “2020-2021 Income Eligibility Guidelines” - Click Here. If you believe you are eligible then please fill out the “2020-2021 Application for Free and Reduced Priced Meals” and submit to the main office of your child’s school as soon as possible - Click Here. Please refer to the guidelines and complete all required information when completing the application. Incomplete applications will not be approved.


# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

Meals for students receiving remote learning –

Weekly pick up of meals will continue to be available. On Monday mornings parents will be able to pick up their child’s meals at the child’s 
home school between 8:00 am and 8:30 am. At that time a parent will be allowed to obtain up to 5 cereal breakfasts and up to 5 frozen lunches 
(one breakfast and one lunch for each day that school is in session that week). In any week where school is closed on Monday, the pickup of meals 
will resume on the next day that school is in session between 8:00 am and 8:30 am. The menu will be posted on the district’s website. A reminder 
will be provided to the families from the school’s principal. It is recommended that each parent bring a carrying bag that can accommodate the number 
of meals being obtained. Prior to the onset of the school year, you were provided a code that is unique to your child. That code must be provided by you, 
along with your child’s full name, to the staff member who provides you the meals at the pick-up location. If for any reason you were not provided the 
code prior to the onset of the school year or have misplaced it, please call the school’s main office to obtain the information. We look forward to 
serving you and are hopeful that you take advantage of this program.

The tables will continue to be set up at the following location:
Road School: Cafeteria entrance on Park Ave.
